# This is the environment agnostic config file. It is used by setting the SPRING_CONFIG_NAME environment variable to
# "deployed-application". By default the application.yml file will be used, which is convenient for local development.

spring:
  profiles:
    active: "#{Octopus.Environment.Name}"

  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    dbcp2:
      driver-class-name: org.h2.Driver
  flyway:
    locations: classpath:db/migration/{vendor}