name: Java CI

on:
  #push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: nelonoel/branch-name@v1.0.1

    - name: Set up JDK 1.11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install Octopus Deploy CLI
      uses: OctopusDeploy/install-octocli@v1
      with:
        version: 7.4.3124

    - name: Update version
      run: mvn versions:set -DnewVersion=0.1.${{ github.run_number }}

    - name: List dependencies
      run: mvn --batch-mode dependency:tree --no-transfer-progress

    - name: Build with Maven
      run: mvn --batch-mode package --file pom.xml -DfinalName=app

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 0.1.${{ github.run_number }}
        release_name: Release 0.1.${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/app.jar
        asset_name: app.0.1.${{ github.run_number }}.jar
        asset_content_type: application/zip

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Main build and push
      if: github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v2
      with:
        push: true
        build-args: VERSION=0.1.${{ github.run_number }}
        tags: octopussamples/randomquotesjava:0.1.${{ github.run_number }}

    - name: Main build Docker build info
      if: github.ref == 'refs/heads/master'
      run: >-
        echo "{
        \"PackageId\": \"octopussamples/randomquotesjava\",
        \"Version\": \"0.1.${{ github.run_number }}\",
        \"BuildUrl\": \"https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}\",
        \"BuildNumber\": \"${{ github.run_number }}\",
        \"Branch\": \"${{ github.ref }}\",
        \"BuildEnvironment\":\"GitHub\",
        \"VcsCommitNumber\":\"${{ github.sha }}\",
        \"VcsCommitUrl\":\"https://github.com/OctopusSamples/RandomQuotes-Java/commit/${{ github.sha }}\",
        \"VcsType\": \"Git\",
        \"VcsRoot\": \"https://github.com/OctopusSamples/RandomQuotes-Java\",
        \"CommentParser\": \"GitHub\",
        \"Commits\":
        [{\"Id\":\"${{ github.sha }}\", \"LinkUrl\":\"https://github.com/OctopusSamples/RandomQuotes-Java/commit/${{ github.sha }}\", \"Comment\": \"${{ github.event.head_commit.message }}\"}]
        }" > dockerbuildinfo.json; cat dockerbuildinfo.json

    - name: Main push build Info
      if: github.ref == 'refs/heads/master'
      run: >-
        octo build-information
        "--space=${{ secrets.OCTOPUS_SERVER_SPACE }}"
        --server=${{ secrets.OCTOPUS_SERVER_URL }}
        --apiKey=${{ secrets.OCTOPUS_API_KEY }}
        --package-id=octopussamples/randomquotesjava
        --version=0.1.${{ github.run_number }}
        --file=dockerbuildinfo.json

    - name: Branch build and push
      if: github.ref != 'refs/heads/master'
      uses: docker/build-push-action@v2
      with:
        push: true
        build-args: VERSION=0.1.${{ github.run_number }}-${{ env.BRANCH_NAME }}
        tags: octopussamples/randomquotesjava:0.1.${{ github.run_number }}-${{ env.BRANCH_NAME }}

    - name: Main push to Maven
      if: github.ref == 'refs/heads/master'
      run: >-
        mvn --batch-mode deploy:deploy-file
        -DgroupId=com.octopus
        -DartifactId=randomquotes
        -Dversion=0.1.${{ github.run_number }}
        -Dpackaging=jar
        -Dfile=target/app.jar
        -DrepositoryId=github
        -Durl=https://maven.pkg.github.com/OctopusSamples/RandomQuotes-Java
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Branch push to Maven
      if: github.ref != 'refs/heads/master'
      run: >-
        mvn --batch-mode deploy:deploy-file
        -DgroupId=com.octopus
        -DartifactId=randomquotes
        -Dversion=0.1.${{ github.run_number }}-${BRANCH_NAME}
        -Dpackaging=jar
        -Dfile=target/app.jar
        -DrepositoryId=github
        -Durl=https://maven.pkg.github.com/OctopusSamples/RandomQuotes-Java
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Branch build Docker build info
      if: github.ref != 'refs/heads/master'
      run: >-
        echo "{
        \"PackageId\": \"octopussamples/randomquotesjava\",
        \"Version\": \"0.1.${{ github.run_number }}-${BRANCH_NAME}\",
        \"BuildUrl\": \"https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}\",
        \"BuildNumber\": \"${{ github.run_number }}\",
        \"Branch\": \"${{ github.ref }}\",
        \"BuildEnvironment\":\"GitHub\",
        \"VcsCommitNumber\":\"${{ github.sha }}\",
        \"VcsCommitUrl\":\"https://github.com/OctopusSamples/RandomQuotes-Java/commit/${{ github.sha }}\",
        \"VcsType\": \"Git\",
        \"VcsRoot\": \"https://github.com/OctopusSamples/RandomQuotes-Java\",
        \"CommentParser\": \"GitHub\",
        \"Commits\":
        [{\"Id\":\"${{ github.sha }}\", \"LinkUrl\":\"https://github.com/OctopusSamples/RandomQuotes-Java/commit/${{ github.sha }}\", \"Comment\": \"${{ github.event.head_commit.message }}\"}]
        }" > dockerbuildinfo.json; cat dockerbuildinfo.json

    - name: Branch Push Build Info
      if: github.ref != 'refs/heads/master'
      run: >-
        octo build-information
        "--space=${{ secrets.OCTOPUS_SERVER_SPACE }}"
        --server=${{ secrets.OCTOPUS_SERVER_URL }}
        --apiKey=${{ secrets.OCTOPUS_API_KEY }}
        --package-id=octopussamples/randomquotesjava
        --version=0.1.${{ github.run_number }}-${BRANCH_NAME}
        --file=dockerbuildinfo.json

